package it.keypartner.bpmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Basic Parameters to search process instance")
public class BasicParamSearchProcessInstance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String toProcessId;
	private java.lang.String fromProcessId;
	private java.lang.String fromDeploymentId;
	private java.lang.String toDeploymentId;

	public BasicParamSearchProcessInstance() {
	}

	public java.lang.String getToProcessId() {
		return this.toProcessId;
	}

	public void setToProcessId(java.lang.String toProcessId) {
		this.toProcessId = toProcessId;
	}

	public java.lang.String getFromDeploymentId() {
		return this.fromDeploymentId;
	}

	public void setFromDeploymentId(java.lang.String fromDeploymentId) {
		this.fromDeploymentId = fromDeploymentId;
	}

	public java.lang.String getToDeploymentId() {
		return this.toDeploymentId;
	}

	public void setToDeploymentId(java.lang.String toDeploymentId) {
		this.toDeploymentId = toDeploymentId;
	}

	public java.lang.String getFromProcessId() {
		return fromProcessId;
	}

	public void setFromProcessId(java.lang.String fromProcessId) {
		this.fromProcessId = fromProcessId;
	}

	public BasicParamSearchProcessInstance(String toProcessId, String fromProcessId, String fromDeploymentId,
			String toDeploymentId) {
		super();
		this.toProcessId = toProcessId;
		this.fromProcessId = fromProcessId;
		this.fromDeploymentId = fromDeploymentId;
		this.toDeploymentId = toDeploymentId;
	}

	@Override
	public String toString() {
		return "BasicSearchProcessInstance [toProcessId=" + toProcessId + ", fromProcessId=" + fromProcessId
				+ ", fromDeploymentId=" + fromDeploymentId + ", toDeploymentId=" + toDeploymentId + "]";
	}

}