package it.keypartner.bpmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Parameters to search process instance")
public class SearchProcessInstance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String processInstanceId;
	private java.lang.String toProcessId;
	private java.lang.String fromProcessId;
	private java.lang.String fromDeploymentId;
	private java.lang.String toDeploymentId;
	private java.lang.String searchProcessVarName;
	private java.lang.String searchProcessVarValue;

	public SearchProcessInstance() {
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getToProcessId() {
		return this.toProcessId;
	}

	public void setToProcessId(java.lang.String toProcessId) {
		this.toProcessId = toProcessId;
	}

	public java.lang.String getFromDeploymentId() {
		return this.fromDeploymentId;
	}

	public void setFromDeploymentId(java.lang.String fromDeploymentId) {
		this.fromDeploymentId = fromDeploymentId;
	}

	public java.lang.String getToDeploymentId() {
		return this.toDeploymentId;
	}

	public void setToDeploymentId(java.lang.String toDeploymentId) {
		this.toDeploymentId = toDeploymentId;
	}

	public java.lang.String getSearchProcessVarName() {
		return this.searchProcessVarName;
	}

	public void setSearchProcessVarName(java.lang.String searchProcessVarName) {
		this.searchProcessVarName = searchProcessVarName;
	}

	public java.lang.String getSearchProcessVarValue() {
		return this.searchProcessVarValue;
	}

	public void setSearchProcessVarValue(java.lang.String searchProcessVarValue) {
		this.searchProcessVarValue = searchProcessVarValue;
	}

	public java.lang.String getFromProcessId() {
		return fromProcessId;
	}

	public void setFromProcessId(java.lang.String fromProcessId) {
		this.fromProcessId = fromProcessId;
	}

	public SearchProcessInstance(String processInstanceId, String toProcessId, String fromProcessId,
			String fromDeploymentId, String toDeploymentId, String searchProcessVarName, String searchProcessVarValue) {
		super();
		this.processInstanceId = processInstanceId;
		this.toProcessId = toProcessId;
		this.fromProcessId = fromProcessId;
		this.fromDeploymentId = fromDeploymentId;
		this.toDeploymentId = toDeploymentId;
		this.searchProcessVarName = searchProcessVarName;
		this.searchProcessVarValue = searchProcessVarValue;
	}

	@Override
	public String toString() {
		return "SearchProcessInstance [processInstanceId=" + processInstanceId + ", toProcessId=" + toProcessId
				+ ", fromProcessId=" + fromProcessId + ", fromDeploymentId=" + fromDeploymentId + ", toDeploymentId="
				+ toDeploymentId + ", searchProcessVarName=" + searchProcessVarName + ", searchProcessVarValue="
				+ searchProcessVarValue + "]";
	}

}