package it.keypartner.bpmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SearchAllProcInstance implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SearchAllProcInstance() {
    }

}