package it.keypartner.bpmigration;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Variabile Parameters to search process instance")
public class VarParamSearchProcessInstance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String searchProcessVarName;
	private java.lang.String searchProcessVarValue;

	public VarParamSearchProcessInstance() {
	}

	public java.lang.String getSearchProcessVarName() {
		return searchProcessVarName;
	}

	public void setSearchProcessVarName(java.lang.String searchProcessVarName) {
		this.searchProcessVarName = searchProcessVarName;
	}

	public java.lang.String getSearchProcessVarValue() {
		return searchProcessVarValue;
	}

	public void setSearchProcessVarValue(java.lang.String searchProcessVarValue) {
		this.searchProcessVarValue = searchProcessVarValue;
	}

	public VarParamSearchProcessInstance(String searchProcessVarName, String searchProcessVarValue) {
		super();
		this.searchProcessVarName = searchProcessVarName;
		this.searchProcessVarValue = searchProcessVarValue;
	}

	@Override
	public String toString() {
		return "VarParamSearchProcessInstance [searchProcessVarName=" + searchProcessVarName
				+ ", searchProcessVarValue=" + searchProcessVarValue + "]";
	}

}